### ISSUE TITLE
Error: https://registry.yarnpkg.com/@fuel%2fcss: Not found

### ISSUE THREAD

**Issue by pixelsbyeryc** [pedronauck/fuel-design-system#2]
Trying to install dependencies under `./packages/react` not working.

Is it the node version?

---

Arguments: 
`/Users/<User>/.nvm/versions/node/v17.9.0/bin/node /opt/homebrew/Cellar/yarn/1.22.18/libexec/bin/yarn.js`

PATH: 

`/opt/homebrew/sbin:/Users/<User>/.nvm/versions/node/v17.9.0/bin:/Users/<User>/.phpenv/shims:/Users/<User>/.phpenv/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/<User>/.composer/vendor/bin:/Users/<User>/.fig/bin:/Users/<User>/.local/bin`

Yarn version: 
> 1.22.18

Node version: 
> 17.9.0

Platform: 
> darwin x64

Trace: 
```sh
Error: https://registry.yarnpkg.com/@fuel%2fcss: Not found
      at Request.params.callback [as _callback] (/opt/homebrew/Cellar/yarn/1.22.18/libexec/lib/cli.js:66138:18)
      at Request.self.callback (/opt/homebrew/Cellar/yarn/1.22.18/libexec/lib/cli.js:140883:22)
      at Request.emit (node:events:527:28)
      at Request.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.18/libexec/lib/cli.js:141855:10)
      at Request.emit (node:events:527:28)
      at IncomingMessage.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.18/libexec/lib/cli.js:141777:12)
      at Object.onceWrapper (node:events:641:28)
      at IncomingMessage.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by pedronauck** [comment]
That's an internal package of the monorepo (we'are using [Turborepo](https://turborepo.org/)) here. So, first you need to run `pnpm build` in the root of the repo in order to build internal packages and then in the `packages/react` run `pnpm storybook` in order to run Storybook

**Comment by pixelsbyeryc** [comment]
I'm having trouble installing it... Maybe I don't know the correct stack to use, or how to use Turborepo.

**Error:**

```sh
node_modules/.pnpm/turbo@1.2.5/node_modules/turbo: Running postinstall script, failed in 65ms
.../.pnpm/turbo@1.2.5/node_modules/turbo postinstall$ node install.js
│ [turbo] Failed to find package "turbo-darwin-64" on the file system
│ This can happen if you use the "--no-optional" flag. The "optionalDependencies"
│ package.json feature is used by turbo to install the correct binary executable
│ for your current platform. This install script will now attempt to work around
│ this. If that fails, you need to remove the "--no-optional" flag to use turbo.
│ node:internal/modules/cjs/loader:933
│   const err = new Error(message);
│               ^
│ Error: Cannot find module 'turbo'
```

I've tried to run both `pnpm install`  and `pnpm build`, they're both throwing the same error.

Here's the `.pnpm-debug-log`:

```json
{
  "0 debug pnpm:scope": {
    "selected": 1,
    "workspacePrefix": "/Users/<USER>/Projects/design-system"
  },
  "1 error pnpm": {
    "code": "ELIFECYCLE",
    "errno": "ENOENT",
    "syscall": "spawn",
    "file": "sh",
    "pkgid": "@fuel/design-system@0.0.1",
    "stage": "build",
    "script": "turbo run build",
    "pkgname": "@fuel/design-system",
    "err": {
      "name": "pnpm",
      "message": "@fuel/design-system@0.0.1 build: `turbo run build`\nspawn ENOENT",
      "code": "ELIFECYCLE",
      "stack": "pnpm: @fuel/design-system@0.0.1 build: `turbo run build`\nspawn ENOENT\n    at ChildProcess.<anonymous> (/snapshot/dist/pnpm.cjs)\n    at ChildProcess.emit (events.js:376:20)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
    }
  },
  "2 warn pnpm:global": " Local package.json exists, but node_modules missing, did you mean to install?"
}
```
